# Usamos una imagen oficial de Node.js
FROM node:20

# Creamos la carpeta de la app
WORKDIR /app

# Copiamos package.json y package-lock.json
COPY package*.json ./

# Instalamos dependencias
RUN npm install

# Copiamos el resto del código
COPY . .

# Compilamos TypeScript
RUN npm run build

# Comando para iniciar la app
CMD ["npm", "start"]
