# Usamos Node.js 20 como base
FROM node:20

# Creamos la carpeta de la app
WORKDIR /app

# Copiamos package.json y package-lock.json
COPY package*.json ./

# Instalamos dependencias
RUN npm install

# Copiamos todo el código
COPY . .

# Compilamos TypeScript a dist/
RUN npm run build

# Exponemos el puerto que uses (ej: 3000)
EXPOSE 3000

# Comando para iniciar la app
CMD ["npm", "start"]
